api/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^vote/$',views.vote,name="vote"),
	url(r'^get_vote_data/$',views.get_vote_data, name="get_vote_data"),
	url(r'^get_lne_items/$',views.get_lne_items, name="get_lne_items"),
	url(r'^get_community_genres/$',views.get_community_genres, name="get_community_genres"),
	url(r'^get_community_artists/$',views.get_community_artists, name="get_community_artists"),
	url(r'^get_community_songs/$',views.get_community_songs, name="get_community_songs"),
	url(r'^get_community_rhymes/$',views.get_community_rhymes, name="get_community_rhymes"),
	url(r'^get_top_contributors/$',views.get_top_contributors, name="get_top_contributors"),
	url(r'^get_user_voted/$',views.get_user_voted, name="get_user_voted"),

]

mjavantgarde/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.contrib import admin

from django.contrib.auth.models import User

from engine.views import home
from engine.views import search
from engine.views import video

from engine.views import genre
from engine.views import artist
from engine.views import song

from engine.views import about
from engine.views import faq
from engine.views import terms

from engine.views import likely_needs_edits

from engine.views import profile
from engine.views import deactivate_user

from engine.views import RhymeDetailView

from engine.views import RhymeCreateView
from engine.views import RhymeDetailView
from engine.views import RhymeDeleteView

from engine.views import CommunityGenreCreateView
from engine.views import CommunityGenreDeleteView
from engine.views import CommunityArtistCreateView
from engine.views import CommunityArtistDeleteView
from engine.views import CommunitySongCreateView
from engine.views import CommunitySongDeleteView

from engine.views import UserProfileEditView

urlpatterns = [
    url(r'^$', home, name='home'),

    url(r'^api/', include('api.urls')),

    url(r'^search/$',search, name='search'),

    url(r'^about/$',about, name='about'),
    url(r'^faq/$',faq, name='faq'),
    url(r'^terms/$',terms, name='terms'),

    url(r'^likely_needs_edits/$',likely_needs_edits, name='likely_needs_edits'),

    url(r'^genre/(?P<slug>[-\w]+)/$',genre, name='genre'),
    url(r'^artist/(?P<slug>[-\w]+)/$',artist, name='artist'),
    url(r'^song/(?P<slug>[-\w]+)/$',song, name='song'),

    url(r'^(?P<video_id>[-\w]+)/r/(?P<pk>\d+)/(?P<slug>[-\w]+)/$',RhymeDetailView.as_view(),name='rhyme_detail'),

    url(r'^(?P<video_id>[-\w]+)/r/create/$',login_required(RhymeCreateView.as_view()),name='community_rhyme_create'),
    url(r'^(?P<video_id>[-\w]+)/r/delete/(?P<pk>\d+)/(?P<slug>[-\w]+)/$',login_required(RhymeDeleteView.as_view()),name='community_rhyme_delete'),

    url(r'^(?P<video_id>[-\w]+)/genre/define/$',login_required(CommunityGenreCreateView.as_view()),name='community_genre_create'),
    url(r'^(?P<video_id>[-\w]+)/genre/delete/(?P<pk>\d+)/(?P<slug>[-\w]+)/$',login_required(CommunityGenreDeleteView.as_view()),name='community_genre_delete'),

    url(r'^(?P<video_id>[-\w]+)/artist/define/$',login_required(CommunityArtistCreateView.as_view()),name='community_artist_create'),
    url(r'^(?P<video_id>[-\w]+)/artist/delete/(?P<pk>\d+)/(?P<slug>[-\w]+)/$',login_required(CommunityArtistDeleteView.as_view()),name='community_artist_delete'),

    url(r'^(?P<video_id>[-\w]+)/song/define/$',login_required(CommunitySongCreateView.as_view()),name='community_song_create'),
    url(r'^(?P<video_id>[-\w]+)/song/delete/(?P<pk>\d+)/(?P<slug>[-\w]+)/$',login_required(CommunitySongDeleteView.as_view()),name='community_song_delete'),

    url(r'^user/(?P<slug>[-\w]+)/$',profile, name='user_profile'),
    url(r'^edit_profile/$',login_required(UserProfileEditView.as_view()),name='edit_profile'),
    url(r'^deactivate_user/$',deactivate_user, name='deactivate_user'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^(?P<video_id>[-\w]+)/$',video,name='video_detail'),

    
]

engine/models.py
import random
import string
import urllib2
import json
import re

from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse,reverse_lazy
from django.db.models.signals import post_save
from django.db import models

#from django.contrib.postgres.fields import JSONField
from django.contrib.auth.models import User

from vote.models import VoteModel

class JSONField(models.TextField):
    """
    JSONField is a generic textfield that neatly serializes/unserializes
    JSON objects seamlessly.
    Django snippet #1478

    example:
        class Page(models.Model):
            data = JSONField(blank=True, null=True)


        page = Page.objects.get(pk=5)
        page.data = {'title': 'test', 'type': 3}
        page.save()
    """

    #__metaclass__ = models.SubfieldBase

    def from_db_value(self, value, expression, connection, context):
        return self.to_python(value)

    def to_python(self, value):
        if value == "":
            return None

        try:
            if isinstance(value, basestring):
                return json.loads(value)
        except ValueError:
            pass
        return value

    def get_db_prep_save(self, value, *args, **kwargs):
        if value == "":
            return None
        if isinstance(value, dict):
            value = json.dumps(value, cls=DjangoJSONEncoder)
        return super(JSONField, self).get_db_prep_save(value, *args, **kwargs)

# NOTICE
# API_KEY USES "mikejohnsonjr" GOOGLE APP, __NOT__ "rhymebase" GOOGLE APP 
# also in main.py, engine.forms, and engine.views

API_KEY = "AIzaSyDntKKATNzobtgBK9xBeFgBkiE0h5BzbEI"

class Counts(models.Model):
	rhymes = models.BigIntegerField()
	assorted_rhymes = models.BigIntegerField()
	genres = models.BigIntegerField()
	artists = models.BigIntegerField()
	songs = models.BigIntegerField()

#karma for adding rhymes, upvotes, 1/2 karma for upvoting
class Rhyme(VoteModel,models.Model):

	user = models.ForeignKey(User,blank=True,null=True)

	is_community = models.BooleanField(default=False)
	original_rhyme = models.ForeignKey('self',blank=True,null=True)
	community_rhymes = models.ManyToManyField('self',blank=True)

	video_id = models.CharField(max_length=20)
	last_word = models.CharField(max_length=50)
	start = models.CharField(max_length=20)
	duration = models.CharField(max_length=20)
	video_title = models.TextField()
	full_line = models.TextField()
	full_line_raw = models.TextField(blank=True)
	is_assorted = models.BooleanField(default=False)
	date_added = models.DateTimeField(auto_now_add=True,blank=True,null=True)

	slug = models.SlugField(blank=True,null=True,max_length=255)

	likely_needs_editing = models.BooleanField(default=False)

	is_added_to_video = models.BooleanField(default=False)

	def get_published_rhyme(self,*args,**kwargs):
		community_rhymes = self.community_rhymes
		if community_rhymes == []:
			return self
		else:
			votes = {r.id:r.votes_score for r in community_rhymes}
			if votes != {}:
				most_votes = max(votes,key=votes.get)
				if votes[most_votes] > 0:
					return Rhyme.objects.get(id=most_votes)
				else:
					return self
			else:
				return self

	def save(self,*args,**kwargs):

		if not self.slug:
			pr = self.get_published_rhyme()
			fl = pr.full_line
			self.slug = slugify(fl)[:255]

		if not self.last_word:
			words = self.full_line.split(' ')
			last_word = words[-1]
			self.last_word = re.sub('[^a-zA-Z0-9]', '', last_word).lower()
		
		super(Rhyme,self).save(*args,**kwargs)


	def __unicode__(self):
		return unicode(self.full_line)

	def get_absolute_url(self):
		return reverse("rhyme_detail", kwargs={
			'video_id':str(self.video_id),
			'pk':str(self.id),
			'slug':str(self.slug)})

	def get_user_voted(self,user_id):
		if self.votes.exists(user_id,action=0):
			vote = 'voted_up'
		elif self.votes.exists(user_id,action=1):
			vote = 'voted_down'
		else:
			vote = 'not_voted'
		return vote

class AssortedRhymes(models.Model):
	first_rhyme = models.ForeignKey(Rhyme)
	rhymes = models.ManyToManyField(Rhyme,related_name='rhymes')

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	status = models.CharField(max_length=150,blank=True,null=True)
	reddit_username = models.CharField(max_length=50,blank=True,null=True)
	community_genres = models.ManyToManyField('CommunityGenre',blank=True)
	community_artists = models.ManyToManyField('CommunityArtist',blank=True)
	community_songs = models.ManyToManyField('CommunitySong',blank=True)
	rhymes = models.ManyToManyField(Rhyme,blank=True)

	def __unicode__(self):
		return self.user

	def get_karma(self,*args,**kwargs):
		user = self.user
		rhymes = self.rhymes.all()
		genres = self.community_genres.all()
		artists = self.community_artists.all()
		songs = self.community_songs.all()
		karma = 0

		for r in rhymes:
			karma += r.votes.count()
		for g in genres:
			karma += g.votes.count()
		for a in artists:
			karma += a.votes.count()
		for s in songs:
			karma += s.votes.count()

		karma += (len(Rhyme.objects.all()[0].votes.all(user.id))/5.0)
		if len(CommunityGenre.objects.all()) > 0:
			karma += (len(CommunityGenre.objects.all()[0].votes.all(user.id))/5.0)
		if len(CommunityArtist.objects.all()) > 0:
			karma += (len(CommunityArtist.objects.all()[0].votes.all(user.id))/5.0)
		if len(CommunitySong.objects.all()) > 0:
			karma += (len(CommunitySong.objects.all()[0].votes(user.id))/5.0)

		return format(karma,'.2f')

class ArtistManager(models.Manager):

	def get_by_natural_key(self,artist):
		return self.get(artist=artist)

class Artist(models.Model):
	artist = models.CharField(max_length=50,unique=True)
	slug = models.SlugField(max_length=255,blank=True,null=True)
	videos = models.ManyToManyField('Video',blank=True)

	objects = ArtistManager()

	def natural_key(self):
		return self.genre

	def get_picked_videos(self,*args,**kwargs):
		videos = self.videos
		community_artists = [v.get_community_artist() for v in videos]
		picked_video_ids = [ca.video_id for ca in community_artists if cg.artist_object == self]
		picked_videos = [Video.objects.get(video_id=v_id) for v_id in picked_video_ids]
		return picked_videos

	def __unicode__(self):
		return self.artist

	def save(self,*args,**kwargs):
		
		if not self.slug:
			self.slug = slugify(self.artist)

		super(Artist,self).save(*args,**kwargs)

class CommunityArtist(VoteModel,models.Model):
	user = models.ForeignKey(User)
	artist_object = models.ForeignKey(Artist)
	date_added = models.DateTimeField(auto_now_add=True)
	video_id = models.CharField(max_length=20,blank=True,null=True)
	video_title = models.CharField(max_length=255,blank=True)

	is_added_to_video = models.BooleanField(default=False)

	def get_absolute_url(self):
		return reverse("video_detail", kwargs={
			'video_id':str(self.video_id)})

	def __unicode__(self):
		return self.artist_object.artist

	def get_user_voted(self,user_id):
		return self.votes.exists(user_id)

class SongManager(models.Manager):

	def get_by_natural_key(self,song):
		return self.get(song=song)

class Song(models.Model):
	song = models.CharField(max_length=50,unique=True)
	slug = models.SlugField(max_length=255,blank=True,null=True)
	videos = models.ManyToManyField('Video',blank=True)

	objects = SongManager()

	def natural_key(self):
		return self.genre

	def get_picked_videos(self,*args,**kwargs):
		videos = self.videos
		community_songs = [v.get_community_song() for v in videos]
		picked_video_ids = [cs.video_id for cs in community_songs if cg.genre_song == self]
		picked_videos = [Video.objects.get(video_id=v_id) for v_id in picked_video_ids]
		return picked_videos

	def __unicode__(self):
		return self.song

	def save(self,*args,**kwargs):
		
		if not self.slug:
			self.slug = slugify(self.song)

		super(Song,self).save(*args,**kwargs)

	def get_user_voted(self,user_id):
		if self.votes.exists(user_id,action=0):
			vote = 'voted_up'
		elif self.votes.exists(user_id,action=1):
			vote = 'voted_down'
		else:
			vote = 'not_voted'
		return vote

class CommunitySong(VoteModel,models.Model):
	user = models.ForeignKey(User)
	song_object = models.ForeignKey(Song)
	date_added = models.DateTimeField(auto_now_add=True)
	video_id = models.CharField(max_length=20,blank=True,null=True)

	is_added_to_video = models.BooleanField(default=False)
	video_title = models.CharField(max_length=255,blank=True)


	def get_absolute_url(self):
		return reverse("video_detail", kwargs={
			'video_id':str(self.video_id)})

	def __unicode__(self):
		return self.song_object.song

	def get_user_voted(self,user_id):
		if self.votes.exists(user_id,action=0):
			vote = 'voted_up'
		elif self.votes.exists(user_id,action=1):
			vote = 'voted_down'
		else:
			vote = 'not_voted'
		return vote

class GenreManager(models.Manager):

	def get_by_natural_key(self,genre):
		return self.get(genre=genre)

class Genre(models.Model):
	genre = models.CharField(max_length=50,unique=True)
	slug = models.SlugField(max_length=255,blank=True,null=True)
	videos = models.ManyToManyField('Video',blank=True)

	objects = GenreManager()


	def natural_key(self):
		return self.genre

	def get_picked_videos(self,*args,**kwargs):
		videos = self.videos.all()
		community_genres = [v.get_community_genre() for v in videos]
		picked_video_ids = [cg.video_id for cg in community_genres if cg.genre_object == self]
		picked_videos = [Video.objects.get(video_id=v_id) for v_id in picked_video_ids]
		return picked_videos

	def __unicode__(self):
		return self.genre

	def save(self,*args,**kwargs):
		
		if not self.slug:
			self.slug = slugify(self.genre)

		super(Genre,self).save(*args,**kwargs)

class CommunityGenre(VoteModel,models.Model):
	user = models.ForeignKey(User)
	genre_object = models.ForeignKey(Genre)
	date_added = models.DateTimeField(auto_now_add=True)
	video_id = models.CharField(max_length=20,blank=True,null=True)

	is_added_to_video = models.BooleanField(default=False)

	video_title = models.CharField(max_length=255,blank=True)

	def get_absolute_url(self):

mjavantgarde/templates/engine/about.html
{% extends 'base.html' %}

{% block now_playing %}
About
{% endblock %}
{% block player_container_and_vpo %}

<div style="padding:20px; font-size:18px;">
<h1> About Rhymebase </h1>

Rhymebase is the Youtube rhyme database. <a href="http://mikejohnsonjr.com">Mike Johnson Jr</a> started creating Rhymebase in September 2016 as a project to create a <a href="https://www.youtube.com/watch?v=py_DStBkJko">simple video compilation of rhyming lines in Youtube videos</a>. The general web app (without social features; at the time it was merely a public API of the rhymes in the database) was created in a week as a fun project and was sort of left to sit for months as the creator focused on his consulting business. In May 2017, Mike picked the project back up and started collecting more rhymes from Youtube and added social features to the application.<br><br>
On June 10th, 2017, Mike launched Rhymebase as a social app for users to find, edit, and share rhymes (as well as other video metadata) in Youtube videos, with ~270k initial rhymes collected programmatically, all assorted into ~15k rhyme relations.  
</div>
{% endblock %}

mjavantgarde/templates/engine/community_artist_create.html
{% extends 'base.html' %}

{% block player_container_and_vpo %}
<h1> Define Artist </h1>
<form method="POST" action="." style="font-size:11px;padding:20px;">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

{% block rt_link %}
{% if request.GET.original_rhyme %}
{% url 'rhyme_detail' video_id=request.GET.video_id slug=request.GET.slug pk=request.GET.original_rhyme}
{% else %}
{% url 'video_detail' video_id=request.GET.video_id %}
{% endif %}
{% endblock %}

{% block righty %}
<div id="player">
<iframe width="100%" height="300"
src="https://www.youtube.com/embed/{{request.GET.video_id}}?color=white">
</iframe>
</div>
{% endblock %}

{% block more_js %}

<script>
$(document).ready(function(){
    //$('#id_video_id').val(QueryString.video_id);

    var pathname = window.location.pathname;
    var video_id = pathname.split('/')[1];
    $('#id_video_id').val(video_id);

});

    var tag = document.createElement('script');
        tag.src = "http://www.youtube.com/player_api";
        var firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
        var player;
        function onYouTubePlayerAPIReady() {
            player = new YT.Player('player', {
                height: '300',
                width: '640',
                videoId: '{{request.GET.video_id}}',
                events: {
                  'onReady': onPlayerReady,
                }
            });
        }


</script>
{% endblock %}

mjavantgarde/templates/engine/community_genre_create.html
{% extends 'base.html' %}

{% block now_playing %}
Define Genre
{% endblock %}
{% block player_container_and_vpo %}
<div style="padding:20px">
<h1> Define Genre for {{video_id}}</h1>
<form method="POST" action="." style="font-size:11px;padding:20px;">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Submit" style="background:#eee;border:1px solid #111"/>
</form>
</div>
{% endblock %}

{% block rt_link %}
{% if request.GET.original_rhyme %}
{% url 'rhyme_detail' video_id=request.GET.video_id slug=request.GET.slug pk=request.GET.original_rhyme %}
{% else %}
{% url 'video_detail' video_id=video_id %}
{% endif %}
{% endblock %}

{% block righty %}
<div id="player">
<iframe width="100%" height="300"
src="https://www.youtube.com/embed/{{video_id}}?color=white">
</iframe>
</div>
{% endblock %}

{% block more_js %}

<script>
$(document).ready(function(){
	//$('#id_video_id').val(QueryString.video_id);

	var pathname = window.location.pathname;
	var video_id = pathname.split('/')[1];
	$('#id_video_id').val(video_id);

});

	var tag = document.createElement('script');
        tag.src = "http://www.youtube.com/player_api";
        var firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
        var player;
        function onYouTubePlayerAPIReady() {
            player = new YT.Player('player', {
                height: '300',
                width: '640',
                videoId:video_id,
                events: {
                  'onReady': onPlayerReady,
                }
            });
        }


</script>
{% endblock %}

mjavantgarde/templates/engine/community_rhyme_create.html
{% extends 'base.html' %}

{% block now_playing %}

<span class="create-action">Create</span> Rhyme <span class="rhyme-pk"></span>

{% endblock %}
{% block player_container_and_vpo %}

<form method="POST" action="." style="font-size:11px;padding:20px;">
	{% csrf_token %}
	{{form.as_p}}
	<input id="id_original_rhyme" maxlength="20" name="original_rhyme" type="hidden" />
	<input type="submit" value="Submit" />
</form>
{% endblock %}

{% block rt_link %}
{% if request.GET.original_rhyme %}
{% url 'rhyme_detail' video_id=request.GET.video_id slug=request.GET.slug pk=request.GET.original_rhyme}
{% else %}
{% url 'video_detail' video_id=request.GET.video_id %}
{% endif %}
{% endblock %}

{% block right_title %}
"{{request.GET.full_line}}" 
{% endblock %}

{% block righty %}
<div id="player">
<iframe width="100%" height="300"
src="https://www.youtube.com/embed/{{request.GET.video_id}}?color=white">
</iframe>
</div>
{% endblock %}

{% block more_js %}

<script>
$(document).ready(function(){
	if (Utils.queryString().original_rhyme===undefined){
		$('.create-action').text('Create');
	}else{
		$('.create-action').text('Replace');
		$('.rhyme-pk').text(Utils.queryString().original_rhyme);
	}
	$('#id_original_rhyme').val(Utils.queryString().original_rhyme);
	$('#id_video_id').val(Utils.queryString().video_id);
	$('#id_start').val(Utils.queryString().start);
	$('#id_duration').val(Utils.queryString().duration);
	$('#id_full_line').val(Utils.queryString().full_line);
});
	
	var video_id = "{{request.GET.video_id}}"
	if (video_id == ""){
		video_id = window.location.href.split('/')[3]
	}
	var tag = document.createElement('script');
        tag.src = "http://www.youtube.com/player_api";
        var firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
        var player;
        function onYouTubePlayerAPIReady() {
            player = new YT.Player('player', {
                height: '300',
                width: '640',
                videoId: video_id,
                events: {
                  'onReady': onPlayerReady,
                }
            });
        }
        function onPlayerReady(event){
            player.seekTo(parseFloat('{{request.GET.start}}'));
        }
</script>
{% endblock %}

mjavantgarde/templates/engine/community_song_create.html
{% extends 'base.html' %}

{% block player_container_and_vpo %}
<h1> Define Song </h1>
<form method="POST" action="." style="font-size:11px;padding:20px;">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

{% block rt_link %}
{% if request.GET.original_rhyme %}
{% url 'rhyme_detail' video_id=request.GET.video_id slug=request.GET.slug pk=request.GET.original_rhyme}
{% else %}
{% url 'video_detail' video_id=request.GET.video_id %}
{% endif %}
{% endblock %}

{% block righty %}
<div id="player">
<iframe width="100%" height="300"
src="https://www.youtube.com/embed/{{request.GET.video_id}}?color=white">
</iframe>
</div>
{% endblock %}

{% block more_js %}

<script>
$(document).ready(function(){
    //$('#id_video_id').val(QueryString.video_id);

    var pathname = window.location.pathname;
    var video_id = pathname.split('/')[1];
    $('#id_video_id').val(video_id);

});

    var tag = document.createElement('script');
        tag.src = "http://www.youtube.com/player_api";
        var firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
        var player;
        function onYouTubePlayerAPIReady() {
            player = new YT.Player('player', {
                height: '300',
                width: '640',
                videoId: '{{request.GET.video_id}}',
                events: {
                  'onReady': onPlayerReady,
                }
            });
        }


</script>
{% endblock %}

mjavantgarde/templates/engine/genre.html
{% extends 'base.html' %}

{% block player_container_and_vpo %}

<div style="padding:20px;font-size:13px;">
{% for c in content %}
	<a href="{% url 'video_detail' video_id=c.video_id %}">{{c.title}}</a><br>
{% empty %}
No videos in this genre
{% endfor %}

		
</div>


{% endblock %}

{% block info %}

<div class="pagination" style="padding:20px;font-size:14px">
            <span class="step-links">
                {% if results.has_previous %}
                    <a href="?page={{ content.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ content.number }} of {{ content.paginator.num_pages }}.
                </span>

                {% if content.has_next %}
                    <a href="?page={{ content.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
{% endblock %}

mjavantgarde/templates/engine/rhyme_list.html
{% extends 'base.html' %}

{% block now_playing %}
Results for {{request.GET.q}} in {{search_type_key}}s
{% endblock %}

{% block right_title %}
Search Types
{% endblock %}

{% block player_container_and_vpo %}
<div style="padding:20px;font-size:11px" class="thingthang">
	{% if search_type_key == 'rhyme' %}
		{% for item in results %}
			<a href="{% url 'rhyme_detail' video_id=item.video_id pk=item.pk slug=item.slug %}">"{{item}}" - {{item.video_title}}</a>
		{% empty %}
		  	Nothing here.
		{% endfor %}
	{% elif search_type_key == 'genre' %}
		{% for item in results %}
			<a href="{% url 'genre' slug=item.slug %}">{{item.genre}}</a>
		{% empty %}
		  	Nothing here.
		{% endfor %}
	{% elif search_type_key == 'song' %}
		{% for item in results %}
			<a href="{% url 'song' slug=item.slug %}">{{item.song}}</a>
		{% empty %}
		  	Nothing here.
		{% endfor %}
	{% elif search_type_key == 'artist' %}
		{% for item in results %}
			<a href="{% url 'artist' slug=item.slug %}">{{item.artist}}</a>
		{% empty %}
		  	Nothing here.
		{% endfor %}
	{% endif %}
	<div class="pagination" style="font-size:14px">
	    <span class="step-links">
	        {% if results.has_previous %}
	            <a href="?page={{ results.previous_page_number }}&q={{request.GET.q}}&type={{search_type_key}}">previous</a>
	        {% endif %}

	        <span class="current">
	            Page {{ results.number }} of {{ results.paginator.num_pages }}.
	        </span>

	        {% if results.has_next %}
	            <a href="?page={{ results.next_page_number }}&q={{request.GET.q}}&type={{search_type_key}}">next</a>
	        {% endif %}
	    </span>
	</div>
</div>
{% endblock %}

{% block info %}

	<form method="GET" action="{% url 'search' %}">
      <input type="text" name="q" class="test" style="height:23px;font-size:13px;margin-top:1px" placeholder="Search Rhymes..."/>
      <select name="type" id="id_type" style="height:25px;font-size:13px;">
        <option value="rhyme"> Rhymes </option>
        <option value="genre"> Genres </option>
        <option value="artist"> Artist </option>
        <option value="song"> Song </option>
      <input type="submit" value="Search" class="button createStation" style="font-size:13px; background:#222; color:#eee; padding:3.3px;"/>
      </form>

{% endblock %}


{% block righty %}
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" style="width:100%;font-size:13px;" {% if search_type_key == 'rhyme' %}class="active" {% endif %}><a href="{{request.path}}?q={{request.GET.q}}&type=rhyme&page=1">Rhymes</a></li>
    <li style="width:100%; font-size:13px;" role="presentation" {% if search_type_key == 'genre' %}class="active" {% endif %}><a href="{{request.path}}?q={{request.GET.q}}&type=genre&page=1">Genres</a></li>
    <li style="width:100%;font-size:13px;" role="presentation" {% if search_type_key == 'artist' %}class="active" {% endif %}><a href="{{request.path}}?q={{request.GET.q}}&type=artist&page=1">Artists</a></li>
    <li style="width:100%;font-size:13px;" role="presentation" {% if search_type_key == 'song' %}class="active" {% endif %}><a href="{{request.path}}?q={{request.GET.q}}&type=song&page=1">Songs</a></li>
  </ul>
{% endblock %}
{% block content %}

{% endblock %}